### ISSUE TITLE
Support generic OpenAI compatible providers

### ISSUE THREAD

**Issue by RPate97** [token-js/token.js#76]
## Problem
There are a number of other LLM providers that are compatible with the OpenAI API specification such as [LocalAI](https://localai.io/). These providers can be used with Token.js by setting the `baseUrl` field and using the OpenAI provider. However, this behavior isn't documented and there is not great type support for it.

## Solution
Token.js should officially support using any OpenAI API compatible provider. We should do this by creating a new provider and handler `openai-compatible` where the model field is a generic `string`. This provider should error if a `baseUrl` value is not provided. This provider should reuse any logic possible from the OpenAI handler for it's implementation.

**Comment by punkpeye** [comment]
@RPate97 Any chance this will be implemented?

**Comment by RPate97** [comment]
@punkpeye 
Sure thing, thanks for @-ing me on this. I didn't realize it had so many thumbs up. I've implemented the changes described in this issue in #121. Please let me know if you run into any problems with it, or would like better support for any specific provider.

**Comment by punkpeye** [comment]
This is awesome. Thank you
